// <auto-generated />
using System;
using Idionline.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Idionline.Migrations
{
    [DbContext(typeof(IdionlineContext))]
    [Migration("20180915124906_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("Idionline.Models.Idiom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IdiomName");

                    b.Property<char>("Index");

                    b.Property<string>("Interpretation");

                    b.Property<string>("Source");

                    b.Property<DateTime>("UpdateDate");

                    b.HasKey("ID");

                    b.ToTable("Idioms");
                });
#pragma warning restore 612, 618
        }
    }
}
