// <auto-generated />
using Idionline.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Idionline.Migrations
{
    [DbContext(typeof(IdionlineContext))]
    [Migration("20181110121200_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Idionline.Models.Idiom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Definitions");

                    b.Property<string>("IdiomName");

                    b.Property<char>("Index");

                    b.Property<string>("LastEditor");

                    b.Property<string>("Source");

                    b.Property<long>("UpdateTimeUT");

                    b.HasKey("Id");

                    b.ToTable("Idioms");
                });

            modelBuilder.Entity("Idionline.Models.LaunchInf", b =>
                {
                    b.Property<long>("DateUT")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DailyIdiomId");

                    b.Property<string>("DailyIdiomName");

                    b.Property<string>("Text");

                    b.HasKey("DateUT");

                    b.ToTable("LaunchInf");
                });
#pragma warning restore 612, 618
        }
    }
}
